CREATE TABLE IF NOT EXISTS RESTAURANT (
    NAME TEXT,
    NEIGHBORHOOD TEXT,
    CUISINE TEXT,
    REVIEW REAL,
    PRICE TEXT,
    HEALTH TEXT
);

INSERT INTO RESTAURANT (NAME, NEIGHBORHOOD, CUISINE, REVIEW, PRICE, HEALTH) VALUES
('PETER', 'BROOKLYN','STEAK', 4.4, '$$$$','A'),
('JONGRO','MIDTOWN','KOREAN',3.5,'$$','A'),
('POCHA','MIDTOWN','PIZZA',4.0,'$$$','B'),
('LIGHTHOUSE','QUEENS','CHINESE',3.9,'$','A'),
('MINCA','DOWNTOWN','AMERICAN',4.6,'$$$',''),
('MAREA','CHINATOWN','CHINESE',3.0,'$$',''),
('DIRTY CANDY','UPTOWN','ITALIAN',4.9,'$$$$','B'),
('DI FARA PIZZA','BROOKLYN','PIZZA',3.8,'$$','A'),
('GOLDEN UNICORN','UPTOWN','ITALIAN',3.8,'$$','A');

SELECT DISTINCT NEIGHBORHOOD
FROM RESTAURANT;

SELECT DISTINCT CUISINE
FROM RESTAURANT;

SELECT *
FROM RESTAURANT
WHERE CUISINE = 'CHINESE';

SELECT *
FROM RESTAURANT
WHERE REVIEW >= 4.0;

SELECT *
FROM RESTAURANT
WHERE CUISINE = 'ITALIAN'
    AND PRICE IN ('$$','$$$');

SELECT *
FROM RESTAURANT
WHERE PRICE = '$$$';

SELECT *
FROM RESTAURANT
WHERE NAME LIKE '%CANDY%';

SELECT *
FROM RESTAURANT
WHERE NEIGHBORHOOD IN ('MIDTOWN','DOWNTOWN','CHINATOWN');

SELECT *
FROM RESTAURANT
WHERE HEALTH = '' OR HEALTH IS NULL;

SELECT *
FROM RESTAURANT ORDER BY REVIEW DESC
LIMIT 4;